config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dayweeks#index'
  get 'about' => 'pages#about'
  get 'temp' => 'pages#index_templates'


  resources :dayweeks
  resources :lessons
  resources :shedulers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dayweek.rb
class Dayweek < ApplicationRecord
  has_many :shedulers
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :shedulers
end

app/models/numlesson.rb
class Numlesson < ApplicationRecord
  has_many :shedulers
end

app/models/sheduler.rb
class Sheduler < ApplicationRecord
    belongs_to :dayweek
    belongs_to :numlesson
    belongs_to :lesson
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dayweeks_controller.rb
class DayweeksController < ApplicationController
#before_action :authenticate_user!


  def index
    @dayweek = Dayweek.all
    @titlebody = "Дни недели"
  end

  def new
    @dayweek = Dayweek.new
  end
  
  def create
    #render plain: params[:dayweek].inspect
    @dayweek = Dayweek.new(post_params)
    @dayweek.save
    redirect_to @dayweek
  end
  
  def show
    @dayweek = Dayweek.find(params[:id])
  end
    
  def edit
    @dayweek = Dayweek.find(params[:id])
  end
  
  
  def destroy
        @dayweek = Dayweek.find(params[:id])
        @dayweek.destroy
        redirect_to dayweeks_path
  end
    
  def update
      @dayweek = Dayweek.find(params[:id])
        
      if(@dayweek.update(post_params))
          redirect_to dayweeks_path
      else 
          render 'edit'
      end
        
  end
  
  

  private def post_params
      params.require(:dayweek).permit(:brief)
  end
  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    #http_basic_authenticate_with name: "admin", password: "hunter2", except: [:index, :show]
  def index
    @lesson = Lesson.all
    @titlebody = "Предметы"
  end

  def new
    @lesson = Lesson.new
  end

  def create
    #render plain: params[:lesson].inspect
    @lesson = Lesson.new(post_params)
    @lesson.save
    redirect_to lessons_path
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def destroy
        @lesson = Lesson.find(params[:id])
        @lesson.destroy
        redirect_to lessons_path
  end

  def update
      @lesson = Lesson.find(params[:id])

      if(@lesson.update(post_params))
          redirect_to lessons_path
      else
          render 'edit'
      end
  end


  private def post_params
      params.require(:lesson).permit(:brief)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = "информация про расписание заданий"
  end
end

app/controllers/shedulers_controller.rb
class ShedulersController < ApplicationController
#  http_basic_authenticate_with name: "admin", password: "123456", except: [:index, :show]
  def index
    # @sheduler = Sheduler.all
     @dayweeks = Dayweek.all
    @titlebody = "Расписание всех уроков на неделю"
  end

  def new
    @sheduler = Sheduler.new
  end

  def create
    #render plain: params[:post].inspect
    @sheduler = Sheduler.new(post_params)
    if(@sheduler.save)
        redirect_to shedulers_path
    else
        render 'new'
    end
  end

  def show
      @sheduler = Sheduler.find(params[:id])
  end

  def edit
      @sheduler = Sheduler.find(params[:id])
  end

  def destroy
    @sheduler = Sheduler.find(params[:id])
    @sheduler.destroy
    redirect_to shedulers_path
end

def update
    @sheduler = Sheduler.find(params[:id])
    #@path_to_shedulers = Sheduler.find(params[:id])

    if(@sheduler.update(post_params))
        redirect_to dayweek_path(@sheduler.dayweek)
    else
        render 'edit'
    end

end


  private def post_params
      params.require(:sheduler).permit(:dayweek_id, :numlesson_id, :lesson_id, :startlesson, :endlesson)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dayofweek_helper.rb
module DayofweekHelper
end

app/helpers/dayweeks_helper.rb
module DayweeksHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shedulers_helper.rb
module ShedulersHelper
end

app/views/dayweeks/edit.html.erb
<h2>Редактировать:</h2>
<%= form_for :dayweek, url: dayweek_path(@dayweek), method: :patch do |f| %>
    <p>Название<br>
        <%= f.text_field :brief, {class: 'form-control'} %>
    </p>
    <%= f.submit 'сохранить', {class: 'btn btn-sm btn-success'} %>
<% end %>
<hr>
<%= link_to 'удалить..', dayweek_path(@dayweek), method: :delete, data: { confirm: 'Вы уверены?' } , class: 'btn btn-sm btn-outline-danger' %>

app/views/dayweeks/index.html.erb
<%= render 'layouts/body' %>
<% @dayweek.each do |dayweek| %>
<div class = 'alert alert-info'>
    <div class="container">
      <div class="row">
            <div class="col-lg">
              <a href="<%= dayweek_path(dayweek) %>"><h2 class = 'display-4'><%= dayweek.brief %></h2></a>
            </div>
            <div class="col-sm">
            </div>
            <div class="col-xs">
            <% if user_signed_in? %><br>                 
            <% if user_signed_in? %>  <%= link_to 'Редактировать', edit_dayweek_path(dayweek), {class: 'btn btn-secondary btn-sm'}  %><% end %>
            <% end %>
            </div>
          </div>
        </div>        
    </div>






<% end %>

app/views/dayweeks/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1 class = "text-info">Добавление дня недели</h1>
     <br>
     <%= form_for :dayweek, url: dayweeks_path do |f| %>

         <p class = "text-info">Название дня недели</p>
         <%= f.text_field :brief, class: "form-control" %>
         <br>
         <%= f.submit 'Добавить день', class: "btn btn-sm btn-info" %>

       <% end %>


  </div>
</div>

app/views/dayweeks/show.html.erb
<div class="row align-items-center justify-content-center"><h1 class = 'display-3 align=center'><%= @dayweek.brief %></h1></div>
<% @dayweek.shedulers.each do |sheduler| %>
    <div class = 'alert alert-info'>
    <div class="container">
      <div class="row">
            <div class="col-xs">
              <h2 class = 'display-4'><%= sheduler.numlesson.brief %></h2>
            </div>
            <div class="col-lg">
                  <h2 class = 'display-4'><%= sheduler.lesson.brief %></h2>
            </div>
            <div class="col-xs">
                  <h2 class = 'display-4'><%= sheduler.startlesson %></h2>
            </div>
            <div class="col-sm">
                  <h2 class = 'display-4'><%= sheduler.endlesson %></h2>
            </div>
            <div class="col-xs">
            <% if user_signed_in? %><br>                 
            <%= link_to 'Редактировать...', edit_sheduler_path(sheduler), {class: 'btn btn-sm btn-outline-info'}  %>
            <% end %>
            </div>
          </div>
        </div>        
    </div>
<% end %>

app/views/layouts/_body.html.erb
<div class="row align-items-center justify-content-center"><h1 class = 'display-3'><%= @titlebody %></h1></div>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <span class="navbar-brand js-scroll-trigger" href="#page-top">
          <% if user_signed_in? %>
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, data: { confirm: 'Вы уверены?' } , class: 'btn btn-sm btn-outline-danger' %>
          <% else %>
          <%= link_to 'Войти', new_user_session_path, {class: 'btn btn-sm btn-outline-info'}  %>&nbsp<%= link_to 'Зарегистрироваться', new_user_registration_path, {class: 'btn btn-sm btn-outline-info'}  %>
          <% end %>
        </span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                 <a class="nav-link js-scroll-trigger" href="<%= dayweeks_path %>">Расписание</a>
            </li>
                 <a class="nav-link js-scroll-trigger" href="<%= lessons_path %>">Предметы</a>
            </li>
                 <a class="nav-link js-scroll-trigger" href="<%= shedulers_path %>">Расписание на неделю</a>
            </li>

            <% if user_signed_in? %>         
                 <a class="nav-link js-scroll-trigger" href="<%= new_dayweek_path %>">Новый день</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link js-scroll-trigger" href="<%= new_lesson_path %>">Новый предмет</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link js-scroll-trigger" href="<%= new_sheduler_path %>">Новое расписание</a>
             <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shedule</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--<%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class = "container">
    <%= render 'layouts/header' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lessons/edit.html.erb
<h2>Редактировать:</h2>
<%= form_for :lesson, url: lesson_path(@lesson), method: :patch do |f| %>
    <p>Название<br>
        <%= f.text_field :brief, {class: 'form-control'} %>
    </p>
    <%= f.submit 'сохранить', {class: 'btn btn-sm btn-success'} %>
<% end %>
<hr>
<%= link_to 'удалить..', lesson_path(@lesson), method: :delete, data: { confirm: 'Вы уверены?' } , class: 'btn btn-sm btn-outline-danger disabled' %>

app/views/lessons/index.html.erb
<%= render 'layouts/body' %>
<div class='all-posts'>
<% @lesson.each do |lesson| %>
    <div class = 'alert alert-info'>
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <h2 class = 'display-4'><%= lesson.brief %></h2>
        </div>
        <div class="col-xs">
          <% if user_signed_in? %><br>  
          <%= link_to 'Редактировать...', edit_lesson_path(lesson), {class: 'btn btn-sm btn-outline-info'}  %>
          <% end %>
        </div>
      </div>
    </div>
    </div>
<% end %>
</div>

app/views/lessons/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1 class = "text-info">Добавление урока</h1>
     <br>
     <%= form_for :lesson, url: lessons_path do |f| %>

         <p class = "text-info">Название урока</p>
         <%= f.text_field :brief, class: "form-control" %>
         <br>
         <%= f.submit 'Добавить урок', class: "btn btn-sm btn-info" %>

       <% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<h1><%= @lesson.brief %></h1>

app/views/pages/about.html.erb
<div class="container">
<h3 class="info"><%= @heading %></h3>
</div>

app/views/pages/index_templates.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Scrolling Nav - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/scrolling-nav.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>Welcome to Scrolling Nav</h1>
        <p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>
      </div>
    </header>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>About this page</h2>
            <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
            <ul>
              <li>Clickable nav links that smooth scroll to page sections</li>
              <li>Responsive behavior when clicking nav links perfect for a one page website</li>
              <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
              <li>Minimal custom CSS so you are free to explore your own unique design options</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section id="services" class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Services we offer</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact us</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="js/scrolling-nav.js"></script>

  </body>

</html>

app/views/shedulers/edit.html.erb
<h2>Редактировать:</h2>
<%= form_for :sheduler, url: sheduler_path(@sheduler), method: :patch do |f| %>
    
             <p class = "text-info">День недели<br>
        <%= f.select :dayweek_id, options_from_collection_for_select(Dayweek.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
         <p class = "text-info">Номер урока<br>
        <%= f.select :numlesson_id, options_from_collection_for_select(Numlesson.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
         <p class = "text-info">Название урока<br>
        <%= f.select :lesson_id, options_from_collection_for_select(Lesson.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
        <div class="container">
          <div class="row">
            <div class="col-sm">
              <p class = "text-info">Начало урока</p>
              <%= f.text_field :startlesson, class: "form-control" %>
            </div>
            <div class="col-sm">
              <p class = "text-info">Окончание урока</p>
              <%= f.text_field :endlesson, class: "form-control" %>
            </div>
          </div>
        </div>
      </p>
         <%= f.submit 'Сохранить изменения', class: "btn btn-sm btn-info" %>
       <% end %>
<hr>
<%= link_to 'удалить..', sheduler_path(@sheduler), method: :delete, data: { confirm: 'Вы уверены?' } , class: 'btn btn-sm btn-outline-danger' %>

app/views/shedulers/index.html.erb
<%= render 'layouts/body' %>
<hr style="width: 100%; color: white; height: 2px; background-color:white" />
<div class='all-posts'>
  <% @dayweeks.each do |dayweek| %>
  <h1 class="display-4 align=center"><%= dayweek.brief %></h1>
    <% dayweek.shedulers.each do |sheduler| %>
      <div class = 'alert alert-info'>
        <div class="container">
          <div class="row">
            <div class="col-2">
                <h2 class = 'display-4'><%= sheduler.lesson.brief %></h2>
            </div>
          <div class="col-sm">
          </div>
          <div class="col-2">
            <% if user_signed_in? %><br>  
                <%= link_to 'Редактировать...', edit_sheduler_path(sheduler), {class: 'btn btn-sm btn-outline-info'}  %>
            <% end %>
          </div>
        </div>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shedulers/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1 class = "text-info">Новое расписание</h1>
     <br>
     <%= form_for :sheduler, url: shedulers_path do |f| %>


     <% if @sheduler.errors.any? %>
      <% @sheduler.errors.full_messages.each do |msg| %>
        <% if msg == 'Title can\'t be blank' %>
                <div class="alert alert-danger"><%= 'название не может быть пустым' %></div>
            <% elsif msg == 'Title is too short (minimum is 5 characters)' %>
                <div class="alert alert-danger"><%= 'минимальное кол-во символов равно 5' %></div>
            <% else %>
                <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
<% end%>
         <p class = "text-info">День недели<br>
        <%= f.select :dayweek_id, options_from_collection_for_select(Dayweek.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
         <p class = "text-info">Номер урока<br>
        <%= f.select :numlesson_id, options_from_collection_for_select(Numlesson.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
         <p class = "text-info">Название урока<br>
        <%= f.select :lesson_id, options_from_collection_for_select(Lesson.all, "id", "brief"), {}, class: 'form-control' %>
        <br>
        <div class="container">
          <div class="row">
            <div class="col-sm">
              <p class = "text-info">Начало урока</p>
              <%= f.text_field :startlesson, class: "form-control" %>
            </div>
            <div class="col-sm">
              <p class = "text-info">Окончание урока</p>
              <%= f.text_field :endlesson, class: "form-control" %>
            </div>
          </div>
        </div>
      </p>
         <%= f.submit 'Добавить урок', class: "btn btn-sm btn-info" %>
       <% end %>
  </div>
</div>